package:
  name: pixi-editor
  version: "0.2.0"

build:
  noarch: generic
  script:
    - if: unix
      then:
        - mkdir -p $PREFIX/bin
        # first write the shebang, then the rest of the file
        - echo "#!$PREFIX/bin/python" > $PREFIX/bin/pixi-editor-launcher.py
        - cat $RECIPE_DIR/../src/main.py >> $PREFIX/bin/pixi-editor-launcher.py
        - chmod +x $PREFIX/bin/pixi-editor-launcher.py
        - mkdir -p $PREFIX/Menu
        - cp $RECIPE_DIR/menu/menu.json $PREFIX/Menu/pixi-editor.json
        - cp $RECIPE_DIR/menu/pixi-icon.* $PREFIX/Menu/
    - if: win
      then:
        - if not exist "%PREFIX%\Menu" mkdir "%PREFIX%\Menu"
        - copy "%RECIPE_DIR%\menu\menu.json" "%PREFIX%\Menu\pixi-editor.json"
        - copy "%RECIPE_DIR%\menu\pixi-icon.ico" "%PREFIX%\Menu\"

requirements:
  run:
    - pyqt 5.*
    - if: osx
      then: 
        - pyobjc-core